FROM dddmr:l4t_r36

RUN pip3 install --no-dependencies ultralytics-thop==2.0.17
RUN pip3 install --no-dependencies requests==2.32.5
RUN pip3 install --no-dependencies polars==1.34.0
RUN pip3 install --no-dependencies polars-runtime-32==1.34.0
RUN pip3 install --no-dependencies numpy==1.24.4
RUN pip3 install --no-dependencies ultralytics==8.3.221
RUN pip3 install --no-dependencies onnxslim==0.1.72
#RUN pip3 install --no-dependencies onnxruntime-gpu==1.23.2
RUN pip3 install --no-dependencies ml_dtypes==0.5.3
RUN pip3 install --no-dependencies colorama==0.4.6
RUN pip3 install --no-dependencies coloredlogs==15.0.1
RUN pip3 install --no-dependencies flatbuffers==25.9.23
RUN pip3 install --no-dependencies humanfriendly==10.0
WORKDIR /root
CMD ["bash"]